### ISSUE TITLE
Error running imposm read

### ISSUE THREAD

**Issue by Duvel** [omniscale/imposm#46]
Hi,
I'm trying to run imposm in an ubuntu container in docker. When I execute the imposm read command I get this error below and it seems to have stopped.

Any clues?

Kind regards,

Remco Schoen

root@50587c6b0392:/osm_input# imposm --read luxembourg-latest.osm.pbf --overwrite-cache
[08:59:14] ## reading luxembourg-latest.osm.pbf
[08:59:14] coords: 1272k nodes: 25k ways: 181k relations: 1k (estimated)
Process CacheWriterProcess-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/dist-packages/imposm/reader.py", line 117, in run
    cache = self.cache(mode='w', estimated_records=self.estimated_records)
  File "/usr/lib/python2.7/dist-packages/imposm/cache/osm.py", line 46, in nodes_cache
    return self._x_cache(self.nodes_fname, NodeDB, mode, estimated_records)
  File "/usr/lib/python2.7/dist-packages/imposm/cache/osm.py", line 68, in _x_cache
    cache = x_class(x, mode, estimated_records=estimated_records)
  File "tc.pyx", line 104, in imposm.cache.tc.BDB.__init__ (imposm/cache/tc.c:1263)
IOError: 15
Process CacheWriterProcess-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/dist-packages/imposm/reader.py", line 117, in run
Process CacheWriterProcess-5:
    cache = self.cache(mode='w', estimated_records=self.estimated_records)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/imposm/cache/osm.py", line 49, in ways_cache
    return self._x_cache(self.ways_fname, WayDB, mode, estimated_records)
  File "/usr/lib/python2.7/dist-packages/imposm/cache/osm.py", line 68, in _x_cache
    cache = x_class(x, mode, estimated_records=estimated_records)
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "tc.pyx", line 104, in imposm.cache.tc.BDB.__init__ (imposm/cache/tc.c:1263)
    self.run()
  File "/usr/lib/python2.7/dist-packages/imposm/reader.py", line 117, in run
    cache = self.cache(mode='w', estimated_records=self.estimated_records)
  File "/usr/lib/python2.7/dist-packages/imposm/cache/osm.py", line 59, in relations_cache
    return self._x_cache(self.relations_fname, RelationDB, mode, estimated_records)
  File "/usr/lib/python2.7/dist-packages/imposm/cache/osm.py", line 68, in _x_cache
    cache = x_class(x, mode, estimated_records=estimated_records)
  File "tc.pyx", line 104, in imposm.cache.tc.BDB.__init__ (imposm/cache/tc.c:1263)
IOError: 15
IOError: 15
Process CacheWriterProcess-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/dist-packages/imposm/reader.py", line 117, in run
    cache = self.cache(mode='w', estimated_records=self.estimated_records)
  File "/usr/lib/python2.7/dist-packages/imposm/cache/osm.py", line 43, in coords_cache
    return self._x_cache(self.coords_fname, coords_db, mode, estimated_records)
  File "/usr/lib/python2.7/dist-packages/imposm/cache/osm.py", line 68, in _x_cache
    cache = x_class(x, mode, estimated_records=estimated_records)
  File "tc.pyx", line 393, in imposm.cache.tc.DeltaCoordsDB.__init__ (imposm/cache/tc.c:5291)
  File "tc.pyx", line 104, in imposm.cache.tc.BDB.__init__ (imposm/cache/tc.c:1263)
IOError: 15

**Comment by olt** [comment]
Is the working dir (/osm_input) writable?

**Comment by Duvel** [comment]
Yes, it is able to create 4 cache files.

**Comment by olt** [comment]
Looks like an mmap error.  Guess that's not support by the FS?https://github.com/maiha/tokyocabinet/blob/786a1cc39be4678e7dd5724374276c5bc0f78100/tcutil.h#L3708

**Comment by Duvel** [comment]
Could be, docker adds all kinds of layering, but my knowledge isn't good at that point. The OS should be ubuntu 14.04, which seems to support mmap, but I don't know how this translates to the FS.

Docker seems to use UnionFS what should have mmap, but that is only based on a quick google action. Boot2docker seems to use AUFS, which should support it, but I found this issue:
https://github.com/docker/docker/issues/4301

I'm going to give it a try with another fs.

**Comment by Duvel** [comment]
I used this blog:
https://three1415.wordpress.com/2014/12/19/switching-storage-driver-of-boot2docker/

And that worked!

**Comment by olt** [comment]
Great!
